name: sih25
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/rishi.png"

flutter:
  uses-material-design: true
  assets:
    - assets/crop.png
    - assets/rice.png
    - assets/maize.png
    - assets/wheat.png
    - assets/rishi.png
